### ISSUE TITLE
DBM Dashboard

### ISSUE THREAD

**Issue by NewtTheWolf** [dbm-network/mods#625] opened 2021-01-07 03:09 UTC
**Describe the bug**
Almost no link works and unfortunately also not the home page

**To Reproduce**
Go to the homepage of the Dashboard, there is already the first bug

**Comment by FulI-Name** [comment] 2021-01-07 05:48
> **Describe the bug**
> Almost no link works and unfortunately also not the home page
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Go to the homepage of the Dashboard, there is already the first bug
It's not a bug, because it's not even in a working state, I have no idea why you are trying to use it. It hasn't been finished yet. :D

**Comment by NewtTheWolf** [comment] 2021-01-07 18:52
Okey, that it does not work is well explained

But why does it already exist although it is not yet functional?

**Comment by Fisheiyy** [comment] 2021-05-20 22:01
> **Describe the bug**
> Almost no link works and unfortunately also not the home page
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Go to the homepage of the Dashboard, there is already the first bug

irrelevant, and in the works of getting fixed

**Comment by TheMonDon** [comment] 2021-05-27 00:45
Closing this due to the discord announcement: https://discord.com/channels/374961173524643843/375897026136899594/834983230280433675

**Closed by TheMonDon** 2021-05-27 00:45 UTC
Labels: s: unverified, type: bug
