### ISSUE TITLE
Play you tube playlist doesn't stores informations

### ISSUE THREAD

**Issue by ignite-69** [dbm-network/mods#347] opened 2020-05-30 05:00 UTC
**Play you tube playlist** doesn't stores title, duration and requester for which people cannot extract it with store audio info mod and the information comes as undefined

**Comment by HysteriaMC** [comment] 2020-05-30 17:43
I can confirm this.

**Comment by Mobulos** [comment] 2020-06-26 10:54
with the Alpha of _play_youtube.js_ I get the error `Error: Error parsing config: Unexpected token ; in JSON at position 176036` 
But when I use the Beta of _play_youtube.js_ I get that error: `Error with getInfoAsync in play_youtube: Error: This video is unavailable
(node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of undefined
    at Object.action [as Play YouTube Video] (/app/actions/play_youtube.js:172:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
`


PS; That Video is aviable

**Comment by ForceBlood** [comment] 2020-07-08 08:25
`Error: This video is unavailable (node:4)` means that the video is blocked in the region your bot is hosted at which explains why you are getting `TypeError: Cannot read property 'title' of undefined` . Can you please check with some other videos to see if it can play them?

**Comment by Almeeida** [comment] 2020-07-08 21:09
Please use the issue template next time.

**Comment by Mobulos** [comment] 2020-07-08 21:45
> `Error: This video is unavailable (node:4)` means that the video is blocked in the region your bot is hosted at which explains why you are getting `TypeError: Cannot read property 'title' of undefined` . Can you please check with some other videos to see if it can play them?

Now I've tested a bunch of other videos, but none of them is working.
But now ffmpeg allegedly  isn't installed.
But since I haven't changed anything, it still should be installed
and when I try to install it again, it doesn't change any file...

**Comment by TheMonDon** [comment] 2020-07-24 16:57
As per the original issue I will look into seeing if I can add the title, duration, and requester to it.

**Comment by Mobulos** [comment] 2020-07-24 17:29
Okay, thanksAm 24.07.2020 18:57 schrieb TheMonDon <notifications@github.com>:
As per the original issue I will look into seeing if I can add the title, duration, and requester to it.

**Comment by TheMonDon** [comment] 2020-07-26 03:40
I've done the best I can but unfortunately, with the way the DBM queue is currently, it doesn't seem to work with adding the different options correctly.

The best I can do is add the requester to it, but not the title, duration, or thumbnail of a playlist.

**Comment by TheMonDon** [comment] 2020-07-28 15:25
Closing this issue as it's not fixable currently, made a pull request with requester added to it though.

PR: https://github.com/dbm-network/mods/pull/485

**Closed by TheMonDon** 2020-07-28 15:25 UTC
Labels: s: won't fix, type: bug
