### ISSUE TITLE
Check Variable Type returns false on Number 0

### ISSUE THREAD

**Issue by RobertPotjes** [dbm-network/mods#630] opened 2021-01-21 10:46 UTC
**Describe the bug**
Check Variable Type returns false on int 0

Cause Line 119 of action check_variable_type.js
Current: if(variable) {
Should probably be: if(typeof variable !== "undefined") {

**To Reproduce**
1. Create an int 0 variable
2. Check Variable type and compare to number
3. This returns false

**Expected behavior**
> typeof parseInt(0) === "number"
< true

**Comment by RobertPotjes** [comment] 2021-01-21 11:32
With the above mentioned possible fix you would also need to check for NaN
As NaN is false it would previously return false on a compare between NaN and Number. 

Since NaN is part of the Numbers Object it will now return true
> typeof(NaN) === "number"
< true

So check for NaN aswell. 
if(typeof variable !== "undefined" && !isNaN(variable))

This would fix this issue but im not sure if this is the best way

**Comment by almeidx** [comment] 2021-01-21 13:38
Duplicate of https://github.com/dbm-network/mods/issues/630

**Closed by almeidx** 2021-01-21 13:38 UTC
Labels: s: duplicate
