### ISSUE TITLE
Event Trigger: On Interval

### ISSUE THREAD

**Issue by demonesmedia** [dbm-network/mods#745] opened 2021-07-13 03:50 UTC
When you use the event trigger on interval it's executing the actions according to how many servers the bot is in, this must be an issue as I do not want the same message being sent in the same channel 40 just because the bot is in 40 servers.

**Comment by tlfn** [comment] 2021-07-13 03:55
It is not a bug. Also you can change your bot's behavior, go to the support channels

**Comment by Lucasamiel0406** [comment] 2021-07-13 04:44
Use `Scheduled Event` instead of `Interval On`, `Scheduled Event` supports `Run Action Sequence Once` action, differently from `Interval On`, which fully stops if you add it.
Also, `Interval On` is a default event provided by the `bot.js` file itself, you can't just change it with mods or else.

**Comment by TheMonDon** [comment] 2021-07-13 06:56
Closing as the above comments are correct.

**Closed by TheMonDon** 2021-07-13 06:56 UTC
Labels: s: unverified, type: bug
