### ISSUE TITLE
store_shard_info_MOD doesent get shard member ammount properly

### ISSUE THREAD

**Issue by Zerlingg** [dbm-network/mods#653] opened 2021-03-12 08:23 UTC
**Describe the bug**
Total Count of Members (in Current Server's Shard) does not get the proper member count. It is showing 40 members when the bot is on a 100 member server.

**To Reproduce**
1. Have the bot in some servers, make sure it goes over 100 or something just to make it clear
2. Store Total Count of Members (in Current Server's Shard)
3. Send it on a message and check yourself

**Expected behavior**
It should get the current shard's member count, instead of this weird random ammount it gets

**Screenshots**
![image](https://user-images.githubusercontent.com/38077912/110912652-7cb8c300-8314-11eb-9480-d7d7244f67bb.png)
![image](https://user-images.githubusercontent.com/38077912/110912711-8cd0a280-8314-11eb-8f70-e2ac4fb9fd11.png)

**Comment by shinobihaxor** [comment] 2021-03-13 09:23
Not a bug, all of 162 members are not cached, to solve this issue you would need to get intent permissions from Discord for your bot to cache all members, but as far as I'm aware its really hard to receive this permission without a good reason.

**Comment by TheMonDon** [comment] 2021-05-28 08:49
Closing as the above comment is correct.

**Closed by TheMonDon** 2021-05-28 08:49 UTC
Labels: s: unverified, type: bug
